---
title: "Ham cooking"
output: html_notebook
---

```{r}
# Packages
library("dplyr")
library("ggplot2")
library("broom")
```

```{r}
# Read data
raw_data <- read.table("raw_data", header = TRUE, sep = ",")

# Add new time column: minutes after ham was removed from the fridge
time_format = "%H:%M"
time_out_of_fridge <- strptime("6:14", format=time_format)

data <- mutate(
  raw_data,
  minutes = difftime(
    strptime(time, format=time_format),
    time_out_of_fridge,
    units="mins",
  )
)

# Time constants
time_into_oven = as.numeric(
  difftime(
    strptime("9:19", format=time_format), 
    time_out_of_fridge, 
    units="mins",
  )
)

time_oven_lower_temp = as.numeric(
  difftime(
    strptime("9:57", format=time_format), 
    time_out_of_fridge, 
    units="mins",
  )
)

time_out_of_oven = as.numeric(
  difftime(
    strptime("11:52", format=time_format), 
    time_out_of_fridge, 
    units="mins",
  )
)

```

```{r}
# Linear regression to initial warming in room temp
early_data <- filter(data, as.numeric(minutes) <= time_into_oven)
early_fit <- lm(temperature ~ minutes, early_data)

tidy(early_fit)

ggplot(
    data=early_data, 
    mapping=aes(
        x = as.numeric(minutes),
        y = temperature, 
    )
  ) +
  geom_point() +
  stat_smooth(method = "lm", col = "red") 
```

```{r}
# Linear regression to heating in oven at 100 °C
heating_data <- filter(data, between(as.numeric(minutes), time_oven_lower_temp, time_out_of_oven))
heating_fit <- lm(temperature ~ minutes, heating_data)

tidy(heating_fit)

ggplot(
    data=heating_fit, 
    mapping=aes(
        x = as.numeric(minutes),
        y = temperature, 
    )
  ) +
  geom_point() +
  stat_smooth(method = "lm", col = "red") 
```
```{r}
# Linear regression to cooling in room temp after maximum temperature
cooling_data <- filter(data, minutes > 371)
cooling_fit <- lm(temperature ~ minutes, cooling_data)

tidy(early_fit)

ggplot(
    data=cooling_data, 
    mapping=aes(
        x = as.numeric(minutes),
        y = temperature, 
    )
  ) +
  geom_point() +
  stat_smooth(method = "lm", col = "red") 
```

```{r}
# Plot
colours <- c(
  "DATA" = "#000000", 
  "FRIDGE" = "#33CCFF",
  "ROOM" = "#66FF33",
  "HOT" = "#CC0000",
  "WARM" = "#FFFF00"
)

background_data = data.frame(
  x1=c(
    -Inf,
    0,
    time_into_oven,
    time_oven_lower_temp,
    time_out_of_oven
  ),
  x2=c(0,
       time_into_oven,
       time_oven_lower_temp,
       time_out_of_oven,
       Inf
  ),
  colour=c(
    colours["FRIDGE"],
    colours["ROOM"],
    colours["HOT"],
    colours["WARM"],
    colours["ROOM"]
  )
)

alpha <- 0.2

ggplot() +
  # Data points
  geom_point(
    data=data, 
    mapping=aes(
        x = as.numeric(minutes),
        y = temperature, 
    )
  ) +
  # Theme
  theme(plot.title = element_text(hjust = 0.5)) + # Center title
  # Title
  ggtitle("Ham core temperature") +
  # x axis
  scale_x_continuous(
    name = "Time (min)",
    breaks = seq(0,420,60),
    minor_breaks = seq(0,420,60),
    sec.axis = sec_axis(~ . / 60, name = "Time (h)")
  ) +
  # y axis
  scale_y_continuous(
    name = "Temperature (°C)",
    breaks = seq(0,80,20),
    minor_breaks = seq(0,80,20),
  ) +
  # Vertical lines and labels
  geom_hline(
    yintercept = 10,
    linetype = "dashed",
  ) +
  annotate(
    "label", 
    x = 10, 
    y = 10, 
    label = "10 °C",
  ) +
  geom_hline(
    yintercept = 73,
    linetype = "dashed",
  ) +
  annotate(
    "label", 
    x = 10, 
    y = 73, 
    label = "73 °C",
  ) +
  # Background regions
  geom_rect(
    data=background_data,
    mapping=aes(
      xmin=x1,
      xmax=x2,
      ymin=-Inf,
      ymax=Inf,
      fill=colour,
    ),
    alpha=alpha,
  ) + 
  # Legend
  scale_fill_manual(
    "Background", 
    values=background_data$colour, 
    labels=c("Fridge", "Room (22.5 °C)", "Oven (200 °C)", "Oven (100 °C)", "Room (22.5 °C)"),
  ) +
  # Fits
  stat_smooth(
    data=early_data,
    mapping=aes(
        x = as.numeric(minutes),
        y = temperature, 
    ),
    method = "lm", 
    col = "red",
  ) +
  stat_smooth(
    data=heating_data,
    mapping=aes(
        x = as.numeric(minutes),
        y = temperature, 
    ),
    method = "lm", 
    col = "red",
  ) +
  stat_smooth(
    data=cooling_data,
    mapping=aes(
        x = as.numeric(minutes),
        y = temperature, 
    ),
    method = "lm", 
    col = "red",
  ) 
```